### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by cooljeanius** [cooljeanius/clojurescript#2]
Looks like there's an issue with `script/uberjar`:
```
$ script/uberjar
+rm -f resources/brepl_client.js
+MAJOR=1
+MINOR=11
++git --no-replace-objects describe --match v1.11
fatal: No names found, cannot describe anything.
+REVISION=
The command "script/uberjar" failed and exited with 128 during .

Your build has been stopped.
```

**Comment by cooljeanius** [comment]
it's weird because the script runs fine locally, so I dunno what's different about the CI environment that causes it to fail there...

**Comment by cooljeanius** [comment]
ok so now the `uberjar` script gets a bit farther, but then it dies when the clojure process it spawns crashes:
```
+clojure -X:uberjar :jar target/cljs.jar :compile-ns :all
Exception in thread "main" java.lang.ExceptionInInitializerError
	at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray, compiling:(clojure/gvec.clj:131:1)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6003)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6319)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6005)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.eval(Compiler.java:6924)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__1621.invoke(core.clj:5893)
	at clojure.core$load.invokeStatic(core.clj:5892)
	at clojure.core$load.doInvoke(core.clj:5876)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$eval3106.invokeStatic(core.clj:6523)
	at clojure.core$eval3106.invoke(core.clj:6523)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.lang.RT.doInit(RT.java:461)
	at clojure.lang.RT.<clinit>(RT.java:331)
	... 1 more
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray
	at clojure.lang.Compiler$NewInstanceMethod.parse(Compiler.java:8206)
	at clojure.lang.Compiler$NewInstanceExpr.build(Compiler.java:7798)
	at clojure.lang.Compiler$NewInstanceExpr$DeftypeParser.parse(Compiler.java:7678)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	... 33 more
The command "script/uberjar" failed and exited with 1 during .

Your build has been stopped.
```

**Comment by cooljeanius** [comment]
OK so I'm just hacking around the errors on GitHub Actions by ignoring them for now; I should still probably fix them properly, though. Also the Appveyor workflow still fails, too.

**Comment by cooljeanius** [comment]
ok I managed to hack around the Appveyor failure, too, but that deserves a proper fix as well...

**Comment by cooljeanius** [comment]
Now seen in PR #47: failure to download ChakraCore from https://aka.ms/chakracore/cc_windows_all_1_8_1 properly... maybe there's an archived copy somewhere? I couldn't seem to find one on the Wayback Machine when I looked...

**Comment by cooljeanius** [comment]
> Now seen in PR #47: failure to download ChakraCore from [aka.ms/chakracore/cc_windows_all_1_8_1](https://aka.ms/chakracore/cc_windows_all_1_8_1) properly... maybe there's an archived copy somewhere? I couldn't seem to find one on the Wayback Machine when I looked...

Seen in PR #48, too...

**Comment by cooljeanius** [comment]
Ah, apparently this is due to chakra-core/ChakraCore#6991 ...

**Comment by cooljeanius** [comment]
> Ah, apparently this is due to [chakra-core/ChakraCore#6991](https://github.com/chakra-core/ChakraCore/issues/6991) ...

OK, I've got a workaround for this for now; leaving this open for replacing hacks with proper fixes...
